### PR TITLE
Move JLLs to own folder

### PR DESCRIPTION
**Pull request by oxinabox**
Companion PR to https://github.com/JuliaRegistries/General/pull/79064

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]
Thanks! Can you also bump the minor version number, so that we can make a new release right after merging?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Thanks!

https://github.com/JuliaRegistries/General/pull/79128

**Comment by DilumAluthge** [comment]
Actually: https://github.com/JuliaRegistries/General/pull/79129

**Comment by KeithWM** [comment]
I am considering overloading the `package_relpath(::AbstractString)` method to group some generated code in a local registry. (Not allowed to share details, sorry.) That would be a similar change to this one, but to me it feels wrong to have to overload this entire method to register packages in a custom location. Would there be some other way to write this method so that it is more elegantly extensible?

**Pull request merged**
